### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [project-trident/Trident-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

**Comment by q5sys** [comment]
These are just forks of their upstream repos, and as such they have to follow the upstream license.  We've forked them so that we can control any future updates from upstream that may break potential future changes we make.  
The Readme lists the upstream repos that we are using.

**Comment by unixorn** [comment]
ok, my bad.
